//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserFlowerShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int ID { get; set; }
        public int IdStatus { get; set; }
        public int IdPayment { get; set; }
        public int IdPoints { get; set; }
        public int IdBasket { get; set; }
        public string Commentt { get; set; }
    
        public virtual Basket Basket { get; set; }
        public virtual PaymentType PaymentType { get; set; }
        public virtual Points Points { get; set; }
        public virtual Status Status { get; set; }
    }
}
